### PR TITLE
Gris 49.deleting participant state properties

### PR DESCRIPTION
**Pull request by RioluM**

### CODE REVIEW

**Review by mrwrob — APPROVED** [review]
I'm not sure why we are removing these properties, but the code looks just fine.

**Review by paulinaborys — COMMENTED** [review]
I thought that it should be an option of deleting these features, more like an update of Participant State. I am not sure 🤔

**Comment by RioluM** [comment]
Concept of participant state was changed and we had to remove these properties. It will be as separate nodes.

**Comment by mrwrob** [comment]
Got it :+1:

**Pull request merged**
