### PR TITLE
Added router and service of model

### PR DESCRIPTION
**Pull request by KKucht**
Added:
- model_model.py
- model_router.py
- model_service.py

### CODE REVIEW

**Review by borsuczek — APPROVED** [review]
Ok

**Review by mrwrob — CHANGES_REQUESTED** [review]
For the future, please add the JIRA ticket number to the PR title. 

Did tests finish successfully on your local machines? I've got 1 error and 1 fail:
```
======================================================================
ERROR: test_save_model_as_owl_without_error (test_model_service.ModelServiceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wrobel/Develop/GRISERA/grisera-framework/ontology_api/tests/test_model_service.py", line 42, in test_save_model_as_owl_without_error
    file_2 = open(path_2)
TypeError: expected str, bytes or os.PathLike object, not NoneType

======================================================================
FAIL: test_get_owl_without_error (test_model_router.ModelRouterTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wrobel/Develop/GRISERA/grisera-framework/ontology_api/tests/test_model_router.py", line 18, in test_get_owl_without_error
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

----------------------------------------------------------------------
Ran 15 tests in 0.271s

FAILED (failures=1, errors=1)

```

**Review by mrwrob — APPROVED** [review]
Good work 👍

**Review by PLangowski — APPROVED** [review]
Looks great

**Pull request merged**
